* Basics

** Create repository

$ git init

** Add file

$ git add filename.txt

** Commit

$ git commit -m "Add filename.txt"

** Add files using wildcard

$ git commit -m '*.txt'

** Removing files

$ git rm "*.txt"

** Reset

$ git reset file.txt

* Remote repositories

** Adding and pushing to remote repository

First, create a GitHub repository on http://github.com.

$ git remote add origin https://github.com/Enfors/syscond.git
$ git push -u origin master

Explanation of "origin" and "master":

- Origin is the remote branch name.
- Master is the default local branch name.

The -u parameter tells git to remember these, so the next time we type:

$ git push

without specifying "origin" and "master".

** Pulling from remote repository

$ git pull origin master

* Branching

** Adding a branch

$ git branch branch_name

Switching to the newly created branch:

$ git checkout branch_name

** Merging branch with master

When you merge, you merge ANOTHER branch INTO your current branch.

First, switch back to master branch:

$ git checkout master

Merge branch called "branch_name" with master:

$ git merge branch_name

Possibly delete the old branch:

$ git branch -d branch_name

** Rebasing and when not to

Rebasing applies all of one branch's commits linearly into another.

*** The golden rule of rebasing

Ask yourself: "Does anyone else look at this branch?"
If the answer is "yes", then don't rebase.

* Tags

There are two types of tags: lightweight and annotated (recommended).

** Lightweight tags

- Like an immutable branch
- Pointer to a specific commit

** Annotated tags

- Also a pointer to a specific commit
- Full objects
- SHA1, tagger name, email, date, message
- Can be signed and verified (GPG)
- Recommended method
